dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: go-add
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: go-cbdz
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: go-dwjw
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: go-jenx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: go-nice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: go-nice-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: node-jenx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: node-livedemo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: python-dwjw
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: react-jenx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: spring-boot-rest-prometheus
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
